version: '3.8'

services:
  front:
    build: ./front
    ports:
      - "3000:3000"
  patient:
    build: ./patient
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/patient
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: m2CstF*MYSQL
  notes:
    build: ./note
    ports:
      - "8081:8081"
    environment:
      MONGODB_URI: mongodb://host.docker.internal:27017/note
  risks:
    build: ./risk
    ports:
      - "8082:8082"
    depends_on:
      - notes
      - patient
  gateway:
    build: ./gateway
    ports:
      - "9101:9101"
    depends_on:
      - patient
      - notes
      - risks
